# Generated by Django 5.2.3 on 2025-07-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('Home', '0002_alter_book_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='Home.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userbooklist',
            field=models.ManyToManyField(blank=True, related_name='borrowed_by', to='Home.book'),
        ),
    ]
