# Generated by Django 5.2.3 on 2025-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_user_wishlist_alter_user_userbooklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='isFine',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
