# Generated by Django 5.2.3 on 2025-07-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_genre',
            field=models.CharField(choices=[('Fiction', 'Fiction (Novels, stories, drama, literary fiction)'), ('Non-Fiction', 'Non-Fiction (Essays, journalism, real-life topics, how-to books)'), ('Science & Technology', 'Science & Technology (Physics, biology, programming, engineering, mathematics)'), ('History & Politics', 'History & Politics (Historical events, government, wars, biographies of leaders)'), ('Children & Young Adult', 'Children & Young Adult (Books for kids, teens, fantasy for younger readers)'), ('Religion & Philosophy', 'Religion & Philosophy (Spiritual texts, beliefs, ethics, thought systems)'), ('Education & Reference', 'Education & Reference (Textbooks, guides, dictionaries, academic materials)')], max_length=40),
        ),
    ]
